apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: systematic-earwig-dotnet-basic
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:fa489fa43a8fd9897d9edef2412627039ba3cb49@sha256:58e9b96d9f5cab2af7a04624365681baaa1e29627b109fac533c8e7b5d69491c
        name: container-image  
